### ISSUE TITLE
Backblaze upload fails

### ISSUE THREAD

**Issue by truthsword** [Forceu/Gokapi#212]
Running docker container with e2e to Backblaze B2... Test files (small) work fine. However, I uploaded a 11 GB file and the progress bar made it to the end after several minutes, but never completed. Logs don't even show the upload.

What am I overlooking? Thanks!

**Comment by Forceu** [comment]
Thanks for the feedback! The default maximum file size is 100GB and the UI would not accept files bigger than that. 

What version are you using? And does the upload status say "processing" or "uploading" after the upload bar goes to the end? Also, did you check the Gokapi output if any errors were logged?

**Comment by Forceu** [comment]
Okay, so this appears to be an error related to Backblaze, I found [this](https://github.com/timmyomahony/craft-remote-backup/issues/11#issuecomment-658023204) Github comment through [Stackoverflow](https://stackoverflow.com/a/76185729/819367)

> B2 app keys can contain non-alphanumeric characters, while S3 secret keys never do. If your app key contains a / or a + then it's possible that this is causing Laravel to send incorrect data.

Is that the case for you? Otherwise maybe try to recreate the bucket and the app key and let me know if that is working. In such a case I could add a note during the setup

**Comment by truthsword** [comment]
Thank you! Interesting information ... but unfortunately of no solution for me.

I created a new B2 bucket and its app key did not contain + or / ... 

I uploaded a 6 B test file, and a 100 MB test file without issue. When I tried a 500 MB the progress line completed to the end, however it remains there with the words “Uploading file...”

![](https://i.imgur.com/uLNWhDz.png).

**Comment by truthsword** [comment]
2 hours later I rechecked and the 500 MB file transfer completed.  
next... 1 GB, 5GB, 15GB

**Comment by Forceu** [comment]
Related to #220
