### ISSUE TITLE
Hourly deletion process doesn't work with AWS

### ISSUE THREAD

**Issue by acourter27** [Forceu/Gokapi#24]
My system is configured to use an S3 bucket. When I press "delete", it deletes the file from S3 without an issue, but if the file is downloaded it doesn't automatically delete. 

Is there a configuration piece I missed, or is this a bug with the AWS configuration?

**Comment by Forceu** [comment]
Thanks for the issue. This is by design and AWS files are deleted after 24 hours. The reason for that is that there is no proper way (that I know of) to find out if the file has been completely downloaded. An AWS file deletion during a download causes an abort of the download, which is why AWS files only expire after 24 hours.

I will add that to the documentation later, of course if anyone knows a reliable way to find out if the AWS download has been finished I would be very much open to implementing this!
