### ISSUE TITLE
Progress Bar does not reflect actual upload progress

### ISSUE THREAD

**Issue by GeorgeAnton1** [Forceu/Gokapi#26]
It seems like the upload bar progresses far quicker than the actual upload progress
This is the current state of my upload according to the admin panel
![image](https://user-images.githubusercontent.com/18126831/129817812-00a38492-e557-4423-ad5d-052ab16fb761.png)

and this is a the current uploaded file size:
![image](https://user-images.githubusercontent.com/18126831/129817872-af1711d7-dc14-40bd-ab1b-24e4d700ecb9.png)

**Comment by Forceu** [comment]
Thank you for your issue. Do you store the files locally or through an S3 service?

**Comment by GeorgeAnton1** [comment]
I store the files locally

**Comment by Forceu** [comment]
The process bar shows the client side progress, I assume the server is still processing the file at that point (some data might still be stored in memory). How long did it take the upload to be finished after it was shown?

The progress bar / upload zone is a different library, but I am considering replacing it at some point.

**Comment by GeorgeAnton1** [comment]
The progress bar finished within 5-10 minutes but the full upload didn't complete until about an hour later.

I should note that the download link wasn't provided until the file was actually uploaded so it seems to be a display issue with the progress bar itself rather than an issue with the way it uploads.

**Comment by Forceu** [comment]
Yes, the problem lays to some extend with the extension. It would be probably a good idea to include a bar that indicates that the upload is being processed. What kind of CPU are you using? I assume the reason why it takes so long is because the whole file is being hashed after the upload has been received.

**Comment by GeorgeAnton1** [comment]
I have dual Xeon E5-2658 v0, however I have docker running inside an LXC container so not all cores are available

**Comment by Forceu** [comment]
Ah according to Wikipedia Intel CPUs only support hardware SHA hashing since 2013, so your CPU has to calculate it conventionally. That is probably the reason why it takes so long for the upload to complete in the end. I will leave this issue open however, ideally the upload view should show a processing status indication after the upload has been completed from client side.

**Comment by GeorgeAnton1** [comment]
Ah that makes sense, cheers for looking into this. Yeah an indicator to show processing status would be a good idea.

**Comment by Forceu** [comment]
Added in 246b3f5edc10fa0314df1d525e1fd1b7c394c542
