### ISSUE TITLE
Allow using ec2 profile or iam role epehemeral creds instead of static credentials

### ISSUE THREAD

**Issue by lookcrabs** [Forceu/Gokapi#27]
## main
I might be too dumb and not understand but it would be great if instead of creating a user and static credentials to instead allow inheriting ephemeral credentials from an I am profile from an ec2 instance. Sorry if this is already possible. I tried to figure this out and couldn't get it to work.

**Comment by Forceu** [comment]
Hi, at the moment only API keys are supported, basically you create a key that is valid for a specific bucket and will only be used by Gokapi, therefore it could be revoked at any time if it gets compromised.

**Comment by Sylphe88** [comment]
Security-wise, it's recommended to use EC2 profile/roles whenever possible instead of AWS IAM secrets (and AWS confirms this) which are tied to a user (and you don't want to manage users in AWS), so it would make sense to consider adding this feature, especially when the aws client supports this type of credentials...
